CREATE DATABASE PROJECTDB
GO
USE PROJECTDB

CREATE TABLE ACCOUNT(
	Username NVARCHAR(20) PRIMARY KEY,
	Pssword NVARCHAR(20),
	Stt NVARCHAR(10)
)
GO

CREATE TABLE HISTORY(
	Username NVARCHAR(20) FOREIGN KEY REFERENCES  ACCOUNT(Username),
	Star INT,
	Desm INT,
	Type_ NVARCHAR(20)
	PRIMARY KEY (Username, Star, Desm)
)
GO



INSERT INTO ACCOUNT VALUES('tuanloc1105', 'Tuanloc123@', 'off'),
('quocduy', 'Quocduy321@', 'off')

SELECT * FROM ACCOUNT

SELECT * FROM HISTORY